name: create pull request

on:
  push:
    branches:
      - dev

env:
  CI: true

jobs:
  pr:
    runs-on: macos-latest
    name: pr
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: username
        run: |
          git config user.name "${{ github.actor }}"

      - name: create pull request
        run: gh pr create -B "master" -r "lauweal" -t "New Translations" -b ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
