name: create pull request

on:
  push:
    branches:
      - dev

env:
  CI: true

jobs:
  pr:
    runs-on: macos-latest
    name: pr
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: username
        run: |
          git config user.name "${{ github.actor }}"

      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: master
          signoff: true
          commit-message: Update report
          committer: Lauweal <lemonpaimc@126.com>
          milestone: 1
          assignees: Lauweal
          reviewers: Lauweal
          labels: |
            report
            automated pr
