name: publish

on:
  pull_request:
    types: [closed]
    branches:
      - master

env:
  CI: true

jobs:
  publish:
    runs-on: macos-latest
    name: publish
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: setup node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: setup node config
        run: |
          npm set registry=https://registry.npmjs.org
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}"

      - name: cache node_modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: build
        run: npm run build

      - name: username
        run: |
          git config user.name "${{ github.actor }}"

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}

      - name: set current version
        shell: bash -ex {0}
        run: |
          CURRENT_VERSION=$(node -p 'require("./package.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.CURRENT_VERSION }}
          release_name: ${{ github.event.pull_request.title }}
          body: |
            ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
          
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.github}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'https://github.com/${{ github.repository }}/releases/tag/v${{ env.CURRENT_VERSION }} is released 🎉'
            })